"""add_status_file_hash

Revision ID: 9052a9ce0fd7
Revises: d3633cf9a5b8
Create Date: 2026-03-09 22:22:01.381280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9052a9ce0fd7'
down_revision: Union[str, Sequence[str], None] = 'd3633cf9a5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_feedbacks', sa.Column('file_hash', sa.String(), nullable=False))
    op.add_column('cv_feedbacks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_cv_feedbacks_file_hash'), 'cv_feedbacks', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_feedbacks_file_hash'), table_name='cv_feedbacks')
    op.drop_column('cv_feedbacks', 'updated_at')
    op.drop_column('cv_feedbacks', 'file_hash')
    # ### end Alembic commands ###
