"""add_statuf_field

Revision ID: d3633cf9a5b8
Revises: 9c7fcadb7d16
Create Date: 2026-03-09 15:21:00.339796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3633cf9a5b8'
down_revision: Union[str, Sequence[str], None] = '9c7fcadb7d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_feedbacks', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_feedbacks', 'status')
    # ### end Alembic commands ###
